name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ✅ Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_KEY }}

      # ✅ Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # ✅ Enable Cloud Run services (optional but useful)
      - name: Enable Cloud Run & Cloud Build APIs
        run: |
          gcloud services enable cloudbuild.googleapis.com run.googleapis.com

      # ✅ Authenticate Docker with Google Container Registry
      - name: Authenticate Docker with Google Container Registry
        run: gcloud auth configure-docker gcr.io

      # ✅ Build and Push Docker Image (Fixed Path)
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/cryptique-backend
          cd backend  # 🔥 Fix: Change to the backend directory
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # ✅ Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/cryptique-backend
          gcloud run deploy cryptique-backend \
            --image $IMAGE_NAME \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --timeout=300
