name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # 🚀 Deploys only when changes are pushed to `main`

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_KEY }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker Auth
        run: gcloud auth configure-docker gcr.io

      - name: Build & Push Docker Image
        run: |
          docker build -t gcr.io/platfrom-cryptique/cryptique-backend .
          docker push gcr.io/platfrom-cryptique/cryptique-backend

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy cryptique-backend \
            --image gcr.io/platfrom-cryptique/cryptique-backend \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
